apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: emo-dev-cluster
spec:
  kafka:
    replicas: 3
    listeners:
      plain: {}
      tls: {}

    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 10Gi               # default 100Gi
        deleteClaim: false
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 10Gi                 # default 100Gi
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}
  kafkaExporter:
    topicRegex: ".*"
    groupRegex: ".*"