{
 "title": "Kafka Connect cluster",
 "description": "Monitor Apache Kafka Connect",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kafka_connect_app_info,namespace)"
    }
   },
   {
    "name": "container",
    "label": "Cluster ID",
    "query": {
     "query": "label_values(kafka_connect_app_info,container)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kafka_connect_app_info{job=\"connect\", namespace=\"$namespace\",container=~\"$container\"},pod)"
    }
   },
   {
    "name": "connector",
    "label": "Connector name",
    "query": {
     "query": "label_values(kafka_connect_connector_task_metrics_pause_ratio{job=\"connect\", namespace=\"$namespace\",container=~\"$container\"},connector)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Tasks Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_connect_worker_metrics_connector_total_task_count{job=\"connect\", namespace=\"$namespace\",pod=~\"$pod\",container=~\"$container\",connector=~\"$connector\"})"
    }
   ]
  },
  {
   "title": "Tasks Running",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_connect_worker_metrics_connector_running_task_count{job=\"connect\", namespace=\"$namespace\",pod=~\"$pod\",container=~\"$container\",connector=~\"$connector\"})"
    }
   ]
  },
  {
   "title": "Tasks Paused",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_connect_worker_metrics_connector_paused_task_count{job=\"connect\", namespace=\"$namespace\",pod=~\"$pod\",container=~\"$container\",connector=~\"$connector\"})"
    }
   ]
  },
  {
   "title": "Tasks Failed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_connect_worker_metrics_connector_failed_task_count{job=\"connect\", namespace=\"$namespace\",pod=~\"$pod\",container=~\"$container\",connector=~\"$connector\"})"
    }
   ]
  },
  {
   "title": "Tasks Unassigned",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_connect_worker_metrics_connector_unassigned_task_count{job=\"connect\", namespace=\"$namespace\",pod=~\"$pod\",container=~\"$container\",connector=~\"$connector\"})"
    }
   ]
  },
  {
   "title": "Tasks Destroyed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_connect_worker_metrics_connector_destroyed_task_count{job=\"connect\", namespace=\"$namespace\",pod=~\"$pod\",container=~\"$container\",connector=~\"$connector\"})"
    }
   ]
  },
  {
   "title": "Connector repartition per status",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (kafka_connect_connector_metrics{job=\"connect\", namespace=\"$namespace\",pod=~\"$pod\",container=~\"$container\",connector=~\"$connector\",status=\"running\"})",
     "legendFormat": "running"
    },
    {
     "expr": "sum (kafka_connect_connector_metrics{job=\"connect\", namespace=\"$namespace\",pod=~\"$pod\",container=~\"$container\",connector=~\"$connector\",status=\"stopped\"})",
     "legendFormat": "stopped"
    },
    {
     "expr": "sum (kafka_connect_connector_metrics{job=\"connect\", namespace=\"$namespace\",pod=~\"$pod\",container=~\"$container\",connector=~\"$connector\",status=\"paused\"})",
     "legendFormat": "paused"
    }
   ]
  },
  {
   "title": "Task repartition per status",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_connect_worker_metrics_connector_running_task_count{job=\"connect\", namespace=\"$namespace\",pod=~\"$pod\",container=~\"$container\",connector=~\"$connector\"})",
     "legendFormat": "running"
    },
    {
     "expr": "sum(kafka_connect_connect_worker_metrics_connector_failed_task_count{job=\"connect\", namespace=\"$namespace\",pod=~\"$pod\",container=~\"$container\",connector=~\"$connector\"})",
     "legendFormat": "failed"
    },
    {
     "expr": "sum(kafka_connect_connect_worker_metrics_connector_paused_task_count{job=\"connect\", namespace=\"$namespace\",pod=~\"$pod\",container=~\"$container\",connector=~\"$connector\"})",
     "legendFormat": "paused"
    },
    {
     "expr": "sum(kafka_connect_connect_worker_metrics_connector_unassigned_task_count{job=\"connect\", namespace=\"$namespace\",pod=~\"$pod\",container=~\"$container\",connector=~\"$connector\"})",
     "legendFormat": "unassigned"
    },
    {
     "expr": "sum(kafka_connect_connect_worker_metrics_connector_destroyed_task_count{job=\"connect\", namespace=\"$namespace\",pod=~\"$pod\",container=~\"$container\",connector=~\"$connector\"})",
     "legendFormat": "destroyed"
    }
   ]
  },
  {
   "title": "Status of connectors",
   "type": "timeseries",
   "description": "Status of connectors over time",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum (kafka_connect_connector_metrics{job=\"connect\", namespace=\"$namespace\",pod=~\"$pod\",container=~\"$container\",connector=~\"$connector\",status!=\"\"}) by (status) ",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Status of tasks",
   "type": "timeseries",
   "description": "Status of tasks over time",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kafka_connect_connect_worker_metrics_connector_running_task_count{job=\"connect\", namespace=\"$namespace\",pod=~\"$pod\",container=~\"$container\",connector=~\"$connector\"})",
     "legendFormat": "running"
    },
    {
     "expr": "sum(kafka_connect_connect_worker_metrics_connector_failed_task_count{job=\"connect\", namespace=\"$namespace\",pod=~\"$pod\",container=~\"$container\",connector=~\"$connector\"})",
     "legendFormat": "failed"
    },
    {
     "expr": "sum(kafka_connect_connect_worker_metrics_connector_paused_task_count{job=\"connect\", namespace=\"$namespace\",pod=~\"$pod\",container=~\"$container\",connector=~\"$connector\"})",
     "legendFormat": "paused"
    },
    {
     "expr": "sum(kafka_connect_connect_worker_metrics_connector_destroyed_task_count{job=\"connect\", namespace=\"$namespace\",pod=~\"$pod\",container=~\"$container\",connector=~\"$connector\"})",
     "legendFormat": "destroyed"
    },
    {
     "expr": "sum(kafka_connect_connect_worker_metrics_connector_unassigned_task_count{job=\"connect\", namespace=\"$namespace\",pod=~\"$pod\",container=~\"$container\",connector=~\"$connector\"})",
     "legendFormat": "unassigned"
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"connect\",namespace=\"$namespace\",container=~\"$container\",pod=~\"$pod\"}[5m])",
     "legendFormat": "{{container}}-{{pod}}"
    }
   ]
  },
  {
   "title": "JVM Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum without(area)(jvm_memory_bytes_used{job=\"connect\",namespace=\"$namespace\",container=~\"$container\",pod=~\"$pod\"})",
     "legendFormat": "{{container}}-{{pod}}"
    },
    {
     "expr": "jvm_memory_bytes_max{job=\"connect\",namespace=\"$namespace\",container=~\"$container\",pod=~\"$pod\",area=\"heap\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "JVM GC time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum without(gc)(rate(jvm_gc_collection_seconds_sum{job=\"connect\",namespace=\"$namespace\",container=~\"$container\",pod=~\"$pod\"}[5m]))",
     "legendFormat": "{{container}}-{{pod}}"
    }
   ]
  },
  {
   "title": "Connector details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Connectors",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_connect_connector_metrics{job=\"connect\", namespace=\"$namespace\",pod=~\"$pod\",container=~\"$container\",connector=~\"$connector\",status!=\"\"}"
    },
    {
     "expr": "kafka_connect_connector_metrics{job=\"connect\", namespace=\"$namespace\",pod=~\"$pod\",container=~\"$container\",connector=~\"$connector\",connector_type!=\"\"}"
    },
    {
     "expr": "kafka_connect_connector_metrics{job=\"connect\", namespace=\"$namespace\",pod=~\"$pod\",container=~\"$container\",connector=~\"$connector\",connector_version!=\"\"}"
    },
    {
     "expr": "kafka_connect_connector_metrics{job=\"connect\", namespace=\"$namespace\",pod=~\"$pod\",container=~\"$container\",connector=~\"$connector\",connector_class!=\"\"}"
    },
    {
     "expr": "sum by (connector) (kafka_connect_connect_worker_metrics_connector_total_task_count{job=\"connect\", namespace=\"$namespace\",pod=~\"$pod\",container=~\"$container\",connector=~\"$connector\"})"
    },
    {
     "expr": "sum by (connector) (kafka_connect_connect_worker_metrics_connector_running_task_count{job=\"connect\", namespace=\"$namespace\",pod=~\"$pod\",container=~\"$container\",connector=~\"$connector\"})"
    },
    {
     "expr": "sum by (connector) (kafka_connect_connect_worker_metrics_connector_failed_task_count{job=\"connect\", namespace=\"$namespace\",pod=~\"$pod\",container=~\"$container\",connector=~\"$connector\"})"
    },
    {
     "expr": "sum by (connector) (kafka_connect_connect_worker_metrics_connector_paused_task_count{job=\"connect\", namespace=\"$namespace\",pod=~\"$pod\",container=~\"$container\",connector=~\"$connector\"})"
    },
    {
     "expr": "sum by (connector) (kafka_connect_connect_worker_metrics_connector_destroyed_task_count{job=\"connect\", namespace=\"$namespace\",pod=~\"$pod\",container=~\"$container\",connector=~\"$connector\"})"
    },
    {
     "expr": "sum by (connector) (kafka_connect_connect_worker_metrics_connector_unassigned_task_count{job=\"connect\", namespace=\"$namespace\",pod=~\"$pod\",container=~\"$container\",connector=~\"$connector\"})"
    }
   ]
  },
  {
   "title": "Connect Worker",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Connect Worker",
     "type": "table-old",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
     "targets": [
      {
       "expr": "kafka_connect_app_info{job=\"connect\", namespace=\"$namespace\",pod=~\"$pod\",container=~\"$container\",client_id!=\"\",start_time_ms!=\"\"}"
      },
      {
       "expr": "kafka_connect_app_info{job=\"connect\", namespace=\"$namespace\",pod=~\"$pod\",container=~\"$container\",client_id!=\"\",version!=\"\"}"
      },
      {
       "expr": "sum by (pod) (kafka_connect_connect_worker_metrics_connector_count{job=\"connect\", namespace=\"$namespace\",pod=~\"$pod\"})"
      },
      {
       "expr": "sum by (pod) (kafka_connect_connect_worker_metrics_connector_startup_success_total{job=\"connect\", namespace=\"$namespace\",pod=~\"$pod\"})"
      },
      {
       "expr": "sum by (pod) (kafka_connect_connect_worker_metrics_connector_startup_failure_total{job=\"connect\", namespace=\"$namespace\",pod=~\"$pod\"})"
      },
      {
       "expr": "sum by (pod) (kafka_connect_connect_worker_metrics_task_count{job=\"connect\", namespace=\"$namespace\",pod=~\"$pod\"})"
      },
      {
       "expr": "sum by (pod) (kafka_connect_connect_worker_metrics_task_startup_success_total{job=\"connect\", namespace=\"$namespace\",pod=~\"$pod\"})"
      },
      {
       "expr": "sum by (pod) (kafka_connect_connect_worker_metrics_task_startup_failure_total{job=\"connect\", namespace=\"$namespace\",pod=~\"$pod\"})"
      }
     ]
    },
    {
     "title": "Network IO Rate",
     "type": "graph",
     "description": "Average number of network operations (reads or writes) on all connections per second",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "kafka_connect_connect_metrics_network_io_rate{job=\"connect\", namespace=\"$namespace\",pod=~\"$pod\",container=~\"$container\",client_id!=\"\"}",
       "legendFormat": "{{pod}}-{{client_id}}"
      }
     ]
    },
    {
     "title": "Incoming Byte Rate",
     "type": "graph",
     "description": "Bytes per second read off all sockets",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 36 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "kafka_connect_connect_metrics_incoming_byte_rate{job=\"connect\", namespace=\"$namespace\",pod=~\"$pod\",container=~\"$container\",client_id!=\"\"}",
       "legendFormat": "{{pod}}-{{client_id}}"
      }
     ]
    },
    {
     "title": "Outgoing Byte Rate",
     "type": "graph",
     "description": "Average number of outgoing bytes sent per second to all servers",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 36 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "kafka_connect_connect_metrics_outgoing_byte_rate{job=\"connect\", namespace=\"$namespace\",pod=~\"$pod\",container=~\"$container\",client_id!=\"\"}",
       "legendFormat": "{{pod}}-{{client_id}}"
      }
     ]
    },
    {
     "title": "Current number of active connections",
     "type": "graph",
     "description": "Current number of active connections",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "connections" }
     ],
     "targets": [
      {
       "expr": "kafka_connect_connect_metrics_connection_count{job=\"connect\", namespace=\"$namespace\",pod=~\"$pod\",container=~\"$container\",client_id!=\"\"}",
       "legendFormat": "{{pod}}-{{client_id}}"
      }
     ]
    },
    {
     "title": "Failed authentication connections",
     "type": "graph",
     "description": "Connections that failed authentication",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 43 },
     "yaxes": [
      { "format": "connections" }
     ],
     "targets": [
      {
       "expr": "kafka_connect_connect_metrics_failed_authentication_total{job=\"connect\", namespace=\"$namespace\",pod=~\"$pod\",container=~\"$container\",client_id!=\"\"}",
       "legendFormat": "{{pod}}-{{client_id}}"
      }
     ]
    },
    {
     "title": "Success authentication connections",
     "type": "graph",
     "description": "Connections that were successfully authenticated using SASL or SSL",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 43 },
     "yaxes": [
      { "format": "connections" }
     ],
     "targets": [
      {
       "expr": "kafka_connect_connect_metrics_successful_authentication_rate{job=\"connect\", namespace=\"$namespace\",pod=~\"$pod\",container=~\"$container\",client_id!=\"\"}",
       "legendFormat": "{{pod}}-{{client_id}}"
      }
     ]
    },
    {
     "title": "IO Ratio",
     "type": "graph",
     "description": "Fraction of time the I/O thread spent doing I/O",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "kafka_connect_connect_metrics_io_ratio{job=\"connect\", namespace=\"$namespace\",pod=~\"$pod\",container=~\"$container\",client_id!=\"\"}",
       "legendFormat": "{{pod}}-{{client_id}}"
      }
     ]
    },
    {
     "title": "Responses received and sent",
     "type": "graph",
     "description": "Responses received and sent per second",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 50 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "kafka_connect_connect_metrics_response_rate{job=\"connect\", namespace=\"$namespace\",pod=~\"$pod\",container=~\"$container\",client_id!=\"\"}",
       "legendFormat": "{{pod}}-{{client_id}}"
      }
     ]
    },
    {
     "title": "Average number of requests",
     "type": "graph",
     "description": "Average number of requests sent per second",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 50 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "kafka_connect_connect_metrics_request_rate{job=\"connect\", namespace=\"$namespace\",pod=~\"$pod\",container=~\"$container\",client_id!=\"\"}",
       "legendFormat": "{{pod}}-{{client_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Worker rebalances",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "($pod) Total number of rebalances",
     "type": "stat",
     "description": "Total number of rebalances",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kafka_connect_connect_worker_rebalance_metrics_completed_rebalances_total{job=\"connect\", namespace=\"$namespace\",pod=~\"$pod\",job=\"connect\",container=~\"$container\"} >= 0"
      }
     ]
    },
    {
     "title": "($pod) Time since last rebalance ",
     "type": "stat",
     "description": "Time since last rebalance",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 34 },
     "repeat": "pod",
     "fieldConfig": { "defaults": { "unit": "clockms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kafka_connect_connect_worker_rebalance_metrics_time_since_last_rebalance_ms{job=\"connect\", namespace=\"$namespace\",pod=~\"$pod\",job=\"connect\",container=~\"$container\"} >= 0"
      }
     ]
    },
    {
     "title": "Rebalances average time",
     "type": "timeseries",
     "description": "Rebalances average time",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_connect_connect_worker_rebalance_metrics_rebalance_avg_time_ms{job=\"connect\", namespace=\"$namespace\",pod=~\"$pod\",container=~\"$container\"}",
       "legendFormat": "{{container}}-{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Task metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Batch Size Average",
     "type": "timeseries",
     "description": "Average size of the batches processed by the connector",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "kafka_connect_connector_task_metrics_batch_size_avg{job=\"connect\", namespace=\"$namespace\",pod=~\"$pod\",container=~\"$container\",connector=~\"$connector\"}",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    },
    {
     "title": "Batch Size Max",
     "type": "timeseries",
     "description": "Maximum size of the batches processed by the connector",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "kafka_connect_connector_task_metrics_batch_size_max{job=\"connect\", namespace=\"$namespace\",pod=~\"$pod\",container=~\"$container\",connector=~\"$connector\"}",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    },
    {
     "title": "Offset commit success percentage",
     "type": "timeseries",
     "description": "Average percentage of the task’s offset commit attempts that succeeded",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "kafka_connect_connector_task_metrics_offset_commit_success_percentage{job=\"connect\", namespace=\"$namespace\",pod=~\"$pod\",container=~\"$container\",connector=~\"$connector\"}",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    },
    {
     "title": "Offset commit Average Time",
     "type": "timeseries",
     "description": "The average time in milliseconds taken by this task to commit offsets",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_connect_connector_task_metrics_offset_commit_avg_time_ms{job=\"connect\", namespace=\"$namespace\",pod=~\"$pod\",container=~\"$container\",connector=~\"$connector\"}",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    },
    {
     "title": "Running ratio",
     "type": "timeseries",
     "description": "The fraction of time this task has spent in the running state.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "kafka_connect_connector_task_metrics_running_ratio{job=\"connect\", namespace=\"$namespace\",pod=~\"$pod\",container=~\"$container\",connector=~\"$connector\"}",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Task Errors metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Total record failures",
     "type": "timeseries",
     "description": "Total number of failures seen by task",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "kafka_connect_task_error_metrics_total_record_failures{job=\"connect\", namespace=\"$namespace\",pod=~\"$pod\",container=~\"$container\",connector=~\"$connector\"}",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    },
    {
     "title": "Total record errors",
     "type": "timeseries",
     "description": "Total number of errors seen by task",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "kafka_connect_task_error_metrics_total_record_errors{job=\"connect\", namespace=\"$namespace\",pod=~\"$pod\",container=~\"$container\",connector=~\"$connector\"}",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    },
    {
     "title": "Total record skipped",
     "type": "timeseries",
     "description": "Total number of records skipped by task",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "kafka_connect_task_error_metrics_total_records_skipped{job=\"connect\", namespace=\"$namespace\",pod=~\"$pod\",container=~\"$container\",connector=~\"$connector\"}",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    },
    {
     "title": "Total errors logged",
     "type": "timeseries",
     "description": "The number of messages that was logged into either the dead letter queue or with Log4j",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "kafka_connect_task_error_metrics_total_errors_logged{job=\"connect\", namespace=\"$namespace\",pod=~\"$pod\",container=~\"$container\",connector=~\"$connector\"}",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    },
    {
     "title": "Total retries",
     "type": "timeseries",
     "description": "Total number of retries made by task",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "kafka_connect_task_error_metrics_total_retries{job=\"connect\", namespace=\"$namespace\",pod=~\"$pod\",container=~\"$container\",connector=~\"$connector\"}",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    },
    {
     "title": "Dead letter queue Produce requests",
     "type": "timeseries",
     "description": "Number of produce requests to the dead letter queue",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "kafka_connect_task_error_metrics_deadletterqueue_produce_requests{job=\"connect\", namespace=\"$namespace\",pod=~\"$pod\",container=~\"$container\",connector=~\"$connector\"}",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    },
    {
     "title": "Dead letter queue Produce failures",
     "type": "timeseries",
     "description": "Number of failed produce requests to the dead letter queue",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "kafka_connect_task_error_metrics_deadletterqueue_produce_failures{job=\"connect\", namespace=\"$namespace\",pod=~\"$pod\",container=~\"$container\",connector=~\"$connector\"}",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Source task metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Source Record Write rate",
     "type": "timeseries",
     "description": "The average per-second number of records output from the transformations and written to Kafka for this task belonging to the named source connector in this worker. This is after transformations are applied and excludes any records filtered out by the transformations.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kafka_connect_source_task_metrics_source_record_write_rate{job=\"connect\", namespace=\"$namespace\",pod=~\"$pod\",container=~\"$container\",connector=~\"$connector\",task!=\"\"}",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    },
    {
     "title": "Source Record Poll rate",
     "type": "timeseries",
     "description": "The average per-second number of records produced/polled (before transformation) by this task belonging to the named source connector in this worker.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "kafka_connect_source_task_metrics_source_record_poll_rate{job=\"connect\", namespace=\"$namespace\",pod=~\"$pod\",container=~\"$container\",connector=~\"$connector\",task!=\"\"}",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    },
    {
     "title": "Source Record Active Count average",
     "type": "timeseries",
     "description": "The average number of records that have been produced by this task but not yet completely written to Kafka.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kafka_connect_source_task_metrics_source_record_active_count_avg{job=\"connect\", namespace=\"$namespace\",pod=~\"$pod\",container=~\"$container\",connector=~\"$connector\",task!=\"\"}",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    },
    {
     "title": "Source Record Active Count max",
     "type": "timeseries",
     "description": "The maximum number of records that have been produced by this task but not yet completely written to Kafka.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kafka_connect_source_task_metrics_source_record_active_count_max{job=\"connect\", namespace=\"$namespace\",pod=~\"$pod\",container=~\"$container\",connector=~\"$connector\",task!=\"\"}",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    },
    {
     "title": "Poll Batch Average time",
     "type": "timeseries",
     "description": "The average time in milliseconds taken by this task to poll for a batch of source records",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_connect_source_task_metrics_poll_batch_avg_time_ms{job=\"connect\", namespace=\"$namespace\",pod=~\"$pod\",container=~\"$container\",connector=~\"$connector\",task!=\"\"}",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    },
    {
     "title": "Poll Batch Max time",
     "type": "timeseries",
     "description": "The maximum time in milliseconds taken by this task to poll for a batch of source records",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_connect_source_task_metrics_poll_batch_max_time_ms{job=\"connect\", namespace=\"$namespace\",pod=~\"$pod\",container=~\"$container\",connector=~\"$connector\",task!=\"\"}",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Sink task metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Record read rate",
     "type": "timeseries",
     "description": "Before transformations are applied, this is the average per-second number of records read from Kafka for the task belonging to the named sink connector in the worker",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "kafka_connect_sink_task_metrics_sink_record_read_rate{job=\"connect\", namespace=\"$namespace\",pod=~\"$pod\",container=~\"$container\",connector=~\"$connector\",task!=\"\"}",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    },
    {
     "title": "Record send rate",
     "type": "timeseries",
     "description": "After transformations are applied, this is the average per-second number of records output from the transformations and sent to the task belonging to the named sink connector in the worker (excludes any records filtered out by the transformations)",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "kafka_connect_sink_task_metrics_sink_record_send_rate{job=\"connect\", namespace=\"$namespace\",pod=~\"$pod\",container=~\"$container\",connector=~\"$connector\",task!=\"\"}",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    },
    {
     "title": "Sink Record Active Count average",
     "type": "timeseries",
     "description": "Average number of records read from Kafka, but that have not yet completely been committed, flushed, or acknowledged by the sink tas",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kafka_connect_sink_task_metrics_sink_record_active_count_avg{job=\"connect\", namespace=\"$namespace\",pod=~\"$pod\",container=~\"$container\",connector=~\"$connector\",task!=\"\"}",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    },
    {
     "title": "Sink Record Active Count max",
     "type": "timeseries",
     "description": "Maximum number of records read from Kafka, but that have not yet completely been committed, flushed, or acknowledged by the sink task",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kafka_connect_sink_task_metrics_sink_record_active_count_max{job=\"connect\", namespace=\"$namespace\",pod=~\"$pod\",container=~\"$container\",connector=~\"$connector\",task!=\"\"}",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    },
    {
     "title": "Offset commit completion rate",
     "type": "timeseries",
     "description": "Average per-second number of offset commit completions that have completed successfully",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "kafka_connect_sink_task_metrics_offset_commit_completion_rate{job=\"connect\", namespace=\"$namespace\",pod=~\"$pod\",container=~\"$container\",connector=~\"$connector\",task!=\"\"}",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    },
    {
     "title": "Offset commit skip rate",
     "type": "timeseries",
     "description": "\tAverage per-second number of offset commit completions that were received too late and skipped, or ignored",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "kafka_connect_sink_task_metrics_offset_commit_skip_rate{job=\"connect\", namespace=\"$namespace\",pod=~\"$pod\",container=~\"$container\",connector=~\"$connector\",task!=\"\"}",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    },
    {
     "title": "Put Batch Average time",
     "type": "timeseries",
     "description": "The average time in milliseconds taken by this task to put a batch of sinks records",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_connect_sink_task_metrics_put_batch_avg_time_ms{job=\"connect\", namespace=\"$namespace\",pod=~\"$pod\",container=~\"$container\",connector=~\"$connector\",task!=\"\"}",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    },
    {
     "title": "Put Batch Max time",
     "type": "timeseries",
     "description": "The maximum time in milliseconds taken by this task to put a batch of sinks records",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_connect_sink_task_metrics_put_batch_max_time_ms{job=\"connect\", namespace=\"$namespace\",pod=~\"$pod\",container=~\"$container\",connector=~\"$connector\",task!=\"\"}",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    },
    {
     "title": "Partition Count",
     "type": "timeseries",
     "description": "The number of topic partitions assigned to this task belonging to the named sink connector in this worker.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kafka_connect_sink_task_metrics_partition_count{job=\"connect\", namespace=\"$namespace\",pod=~\"$pod\",container=~\"$container\",connector=~\"$connector\",task!=\"\"}",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    }
   ]
  }
 ]
}