{
 "title": "Zookeeper cluster",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(zookeeper_version, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Health Check",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Zookeeper nodes online",
   "type": "stat",
   "description": "Quorum Size of Zookeeper ensemble",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(zookeeper_nodecount{job=\"zookeeper\",namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Alive Connections",
   "type": "stat",
   "description": "Number of Alive Connections",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(zookeeper_numaliveconnections{job=\"zookeeper\",namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Outstanding Requests",
   "type": "timeseries",
   "description": "Number of queued requests in the server. This goes up when the server receives more requests than it can process",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "zookeeper_outstandingrequests{job=\"zookeeper\",namespace=\"$namespace\"}",
     "legendFormat": "{{server_id}}:{{member_type}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Number of ZNodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(zookeeper_nodecount{job=\"zookeeper\",namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Number of Watchers",
   "type": "stat",
   "description": "Number of Watchers",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(zookeeper_watchcount{job=\"zookeeper\",namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{job=\"zookeeper\",namespace=\"$namespace\"}[5m])*100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "JVM Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum without(area)(jvm_memory_bytes_used{job=\"zookeeper\",namespace=\"$namespace\"})",
     "legendFormat": "Used:{{instance}}"
    },
    {
     "expr": "jvm_memory_bytes_max{job=\"zookeeper\",namespace=\"$namespace\",area=\"heap\"}",
     "legendFormat": "Max:{{instance}}"
    }
   ]
  },
  {
   "title": "Time spent in GC",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum without(gc)(rate(jvm_gc_collection_seconds_sum{job=\"zookeeper\",namespace=\"$namespace\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Request Latency - Minimum",
   "type": "timeseries",
   "description": "Amount of time it takes for the server to respond to a client request",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "zookeeper_minrequestlatency{job=\"zookeeper\",namespace=\"$namespace\"}",
     "legendFormat": "{{server_id}}:{{member_type}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Request Latency - Average",
   "type": "timeseries",
   "description": "Amount of time it takes for the server to respond to a client request",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "zookeeper_avgrequestlatency{job=\"zookeeper\",namespace=\"$namespace\"}",
     "legendFormat": "{{server_id}}:{{member_type}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Request Latency - Maximum",
   "type": "timeseries",
   "description": "Amount of time it takes for the server to respond to a client request",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "zookeeper_maxrequestlatency{job=\"zookeeper\",namespace=\"$namespace\"}",
     "legendFormat": "{{server_id}}:{{member_type}} ({{instance}})"
    }
   ]
  }
 ]
}