apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-app
  namespace: confluent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-app
  template:
    metadata:
      labels:
        app: kafka-app
    spec:
      containers:
      - name: kafka-app
        image: x00193216/kafka-app:latest
        ports:
        - containerPort: 8080
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka.confluent.svc.cluster.local:9092"